In [1]:
import numpy as np
import pandas as pd

In [2]:
df_old = pd.read_csv('metadata_old.csv')
df_new = pd.read_csv('metadata_new.csv')

In [3]:
df_old.head()

,video_id,category,tag,title,description
0,994a5e59391f7cdcac87b83ac97df50d,Спорт,Экстрим,Кинул вызов команде DiMaTyArIk SCHOOL,Кинул вызов команде DiMaTyArIk SCHOOL
1,3525516efb0d30911e13829e3d5152e3,Спорт,Экстрим,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL
2,768929af55490246ed4b1496b9e98977,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
3,3df5d0c1f2e4a91c63cebffc14c8c467,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
4,162df7df705937f64947c2dd89605d10,Спорт,Экстрим,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2

In [4]:
df_new.head()

,video_id,category,tag,title,description
0,994a5e59391f7cdcac87b83ac97df50d,Спорт,Экстрим,Кинул вызов команде DiMaTyArIk SCHOOL,Кинул вызов команде DiMaTyArIk SCHOOL
1,3525516efb0d30911e13829e3d5152e3,Спорт,Экстрим,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL,ФИНАЛ ЗАРУБЫ с DiMaTyArIk SCHOOL
2,768929af55490246ed4b1496b9e98977,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
3,3df5d0c1f2e4a91c63cebffc14c8c467,Спорт,Экстрим,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...,Принял ЖЁСТКИЙ Вызов От Канала DiMaTyArIk SCHO...
4,162df7df705937f64947c2dd89605d10,Спорт,Экстрим,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2,Плачу ЗА УСПЕХ Кровью и Потом | Путь к ЧМ#2

In [8]:
df_old.video_id.count()

np.int64(7620)

In [10]:
df_new.video_id.count()

np.int64(7220)

In [11]:
df_old.video_id.count() - df_new.video_id.count()

np.int64(400)

In [13]:
count = 0
for video_id in df_old.video_id.value_counts():
    if video_id > 1:
        count += 1
print(count)

345

In [16]:
df_old.category.value_counts()

category
Спорт                           200
Путешествия                     200
Люди и блоги                    200
Хобби                           200
Видеоигры                       200
Разное                          200
Лайфстайл                       200
Лайфхаки                        200
Телепередачи                    200
Юмор                            200
Авто-мото                       200
Сериалы                         200
Музыка                          200
Развлечения                     200
Обучение                        200
Фильмы                          200
Наука                           200
Новости и СМИ                   200
Технологии и интернет           200
Детям                           200
Красота                         200
Животные                        200
Политика                        200
Здоровье                        200
Мультфильмы                     200
Культура                        200
Еда                             200
Аниме                           200
Психология                      200
Техника и оборудование          200
Интервью                        200
Эзотерика                       200
Сад и огород                    200
Бизнес и предпринимательство    200
Строительство и ремонт          194
Обзоры и распаковки товаров     194
Аудиокниги                      112
Природа                          77
Охота и рыбалка                  70
Дизайн                           64
Религия                          60
Недвижимость                     30
Аудио                            19
Name: count, dtype: int64

In [14]:
df_new.category.value_counts()

category
Массовая культура                      1000
Фильмы и анимация                       800
Дом и сад                               458
Телевидение                             400
Информационные технологии               400
Новости и политика                      400
Музыка и аудио                          331
Путешествия                             277
Спорт                                   270
Транспорт                               200
Хобби и интересы, Массовая культура     200
Хобби и интересы                        200
Игры                                    200
Наука                                   200
Стиль и красота                         200
Животные                                200
Образование                             200
Бизнес и финансы                        200
Здоровый образ жизни                    200
Карьера                                 200
Еда и напитки                           200
Медицина                                200
Покупки                                 194
Религия и духовность                     60
Недвижимость                             30
Name: count, dtype: int64